### ISSUE TITLE
Unable to reproduce tutorial (observers not working)

### ISSUE THREAD

**Issue by AlexGreason** [GoodAI/BrainSimulator#8]
I was attempting to follow through the Brain Simulator tutorial, but I encountered some problems.
1. No observers work. At all. They go from "box with red cross in it" to "box with white box in it", but that's all they do.
2. If observers are present, then the program runs for a few steps when told to run, then pauses. If no observers are present, it runs at thousands of steps per second as expected.
3. (separate issue)(note: the tutorial used MNIST world) The arrow from the 'bitmap' input said it had a dimension (if that's what the number in the middle of the arrow from one thing to another means) of 784, as expected, but the arrow from 'label' said it had a dimension of 1, whereas in the tutorial video it said 10.

Now, this may all be my own fault and unresolvable on your part. As CUDA 7 fails to install on my machine, I am using CUDA 7.5, and got the dlls that Brain Simulator needs by downloading and unpacking, but not installing, CUDA 7, then copying over the four relevant dlls (I encountered the same level of functionality by just renaming the relevant CUDA 7.5 dlls to end in _70 rather than _75, but that isn't saying much.). If this is the problem, I'll just wait until either Brain Simulator supports CUDA 7.5 properly or I have access to another machine.

**Comment by MartinBalek** [comment]
ad 3. - by default label returns a float with index of given MNIST number. If you want vector with 10 values (1.0 set for the index, 0.0 otherwise) switch Binary property in Output section of MNISTWorld properties to True (click the icon of globe on the workspace and World properties are then in the top right grid). Then you get the same setting as in tutorial. 

Concerning CUDA 7.5 - we use ManagedCuda to wrap CUDA and it is not yet available for 7.5 (as it is still RC). One possibility would be to try BrainSimulator with CUDA 6.5 - for this you need to replace not only nVidia's DLLs but also libraries related to ManagedCuda (http://managedcuda.codeplex.com/releases/view/129423)

It is hard to get some hint for 1. and 2. as it seems that your CUDA libraries are in some unstable state.
